version: "3.9"
services:
  test:
    build: .
    container_name: test
    ports:
      - "8000/8000"
    restart: unless-stopped
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: